import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import ReduxProvider from "./Provideers/ReduxProvider"
import AuthModal from "./components/AuthenticationModal"
import NavBar from "./components/NavBar"
import { AuthProvider } from "./Provideers/AuthenticationProvider"
import AppShell from "./components/AppShell"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <AuthProvider>
            <AuthModal />
            <NavBar />
            <AppShell>
              {children}
            </AppShell>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}